# This is a basic workflow to help you get started with Actions

name: C Compile

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ftp_cred
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: ls
      #- name: Compiling C Program
      #  run: |
      #   cd C
      #   gcc -v
      #   gcc sample.c -o sample
      #   ./sample
      # Runs a set of commands using the runners shell
      - name: Uploading Files to a Ftp Server 
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo $FTP_SERVER  
      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USER}}
          password: ${{ secrets.FTP_PASS }}
          
        
